### PR TITLE
[EXPENSE] fix #111

### LINKED ISSUE #111: [請款狀態] 擴充既有申請單狀態 - `02-01 API`
## 使用者故事

身為財務組，我希望將狀態列表擴充為「已申請、審核中、出款中、已出款、已完成」，以讓整的請款流程裡的不同負責人，都有獨立對應的狀態可供檢核

## 功能驗證

1. 將請款申請單的狀態( `models/expensedb.py::status` )，擴充為「已申請、審核中、出款中、已出款、已完成」
2. 原本的 `2 - 處理中` ，對應為 `2 - 審核中`
3. 確認不會讓既有年份的 UI 或其他邏輯壞掉
4. 確認新的狀態清單，可以顯示在既有 UI 中，並能彼此切換

### PR DESCRIPTION
**Pull request by oceanchad**
1. Add status and its relative templates
2. Update status 2
3. Done
4. Done

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #111

## What is the new behavior?

- 處理中擴充為審核中和出款中
- 確認不會影響其他UI
- Icon更新

### CODE REVIEW

**Comment by toomore** [comment]
@oceanchad pull `main` 一下，有修正在 actions 中 ubuntu 22.04 的問題。

**Review by ddio — APPROVED** [review]
LGTM!

**Comment by ddio** [comment]
@toomore  發現你要點 approve ，這個 PR 才可以上去 XD

**Comment by toomore** [comment]
https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits

**Review by toomore — APPROVED** [review]

**Comment by toomore** [comment]
@oceanchad 目前看起來可以被 merge 了！我這幾天和 #130 一起合併，感謝！

**Pull request merged**
